# Conda environment for Gammapy version 1.0.2
# Install:    conda env create -f gammapy-1.0.2-environment.yml
# Activate:   conda activate gammapy-1.0.2
# Deactivate: conda deactivate

name: gammapy-1.0.2

channels:
  - conda-forge
  - sherpa

variables:
  PYTHONNOUSERSITE: "1"

dependencies:
  - gammapy=1.0.2
  - python=3.10
  - ipython=8.7.0
  - cython
  - jupyter
  - jupyterlab=3.5
  - pyyaml=6.0
  - click=8.1.3
  - numpy=1.26
  - scipy=1.11
  - pandas=2.1
  - matplotlib=3.8
  - astropy=6.0
  - regions=0.8
  - iminuit=2.24
  - sherpa=4.15
  - healpy=1.16.1
  - naima=0.10
  - pydantic=1.9
  - emcee=3.1
  - corner=2.2
  - pip
  - requests
  - tqdm



    